org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.20
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1
mod_id=hall
mod_name=RottenRuins:The Hall
mod_license=MIT
mod_version=0.4.0
mod_group_id=org.bytechen
mod_authors=ByteChen
mod_description=A Minecraft mod about rotten ruins and hall
systemProp.net.minecraftforge.gradle.check.certs=false